version: "3.8"
services:
  dinebot:
    container_name: dinebot
    image: dinebot
    build: .
    volumes:
      - ./:/app
    ports:
      - "${CHAINLIT_PORT}:${CHAINLIT_PORT}"
    healthcheck:
      test: curl --fail http://localhost:${CHAINLIT_PORT}/login || exit 1
      interval: 10s
      timeout: 3s
      retries: 5
    env_file:
      - .env
